### ISSUE TITLE
参加登録リンクを最新化してほしい

### ISSUE THREAD

**Issue by yumechi** [prickathon/prickathon.github.io#24]
なんかクリックしたら1個目のプリッカソンに飛んだけど、最新のプリッカソン（今回で言えば https://prickathon.connpass.com/event/84874/ ） へのリンクにした方がいいのでは？

毎回メンテするが面倒であれば、 connpass のGroupページ（ https://prickathon.connpass.com/ )でも良いと思う

**Comment by entyo** [comment]
@yumechi ありがとうございます！！GroupページのURLにしようかと思います:pray:
