### ISSUE TITLE
「続きを読む」が動かない

### ISSUE THREAD

**Issue by sue445** [prickathon/prickathon.github.io#39]
「続きを読む」をクリックしても何も起きません。

コンソールを見ると404エラーが出ているのでこいつが怪しそうです

![image](https://user-images.githubusercontent.com/608755/46285104-2d073680-c5b5-11e8-8cad-77fcafe0b1b4.png)

**Comment by takanakahiko** [comment]
極限対応！

**Comment by takanakahiko** [comment]
直ってなかった

**Comment by takanakahiko** [comment]
# 原因

jekyllが勝手に動いて，'_' で始まるディレクトリ( `_nuxt/` )が無視されていた

# 対策

`/static` つまり masterブランチのトップに `.nojekyll` を配置

https://github.com/prickathon/prickathon.github.io/commit/582f0ba4ad1d14504033a9e36399fb1c9c74e2f5

# 参考

https://blog.github.com/2009-12-29-bypassing-jekyll-on-github-pages/

# メモ

- `https://nuxtjs.org/faq/github-pages/` が説明として不完全では
- もしかしたら `push-dir` が吸収してくれている可能性があり，要検証
- なかったら `https://github.com/nuxt/docs/blob/master/en/faq/github-pages.md` にプルリク出す

**Comment by takanakahiko** [comment]
【ちなみに】

`.nojekyll` は勝手に作られるもよう．
`static/` に置く必要なさそうなので要検証．

https://github.com/nuxt/nuxt.js/issues/1098#issuecomment-315779072
